#!/usr/bin/env fish


set jobs (sac $argv | grep -E "cpu.*(FAIL|TIMEOUT)" | cut -f 3 -d" ")
echo
echo (count $jobs) jobs failed.
echo $jobs
echo
for j in $jobs
  set jj (echo $j | sed "s|_|-|")
  find results/*/output -iname "output-$jj.txt" -exec cat '{}' ';'
end
